// Code generated by MockGen. DO NOT EDIT.
// Source: internal/controller/http/handlers.go

// Package service is a generated GoMock package.
package service

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ibeloyar/gophermart/internal/model"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockService) CreateOrder(userID int64, orderNumber string) *model.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", userID, orderNumber)
	ret0, _ := ret[0].(*model.APIError)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockServiceMockRecorder) CreateOrder(userID, orderNumber interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockService)(nil).CreateOrder), userID, orderNumber)
}

// GetBalance mocks base method.
func (m *MockService) GetBalance(userID int64) (*model.Balance, *model.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", userID)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(*model.APIError)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockServiceMockRecorder) GetBalance(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockService)(nil).GetBalance), userID)
}

// GetOrders mocks base method.
func (m *MockService) GetOrders(userID int64) ([]model.Order, *model.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", userID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(*model.APIError)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockServiceMockRecorder) GetOrders(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockService)(nil).GetOrders), userID)
}

// GetWithdraws mocks base method.
func (m *MockService) GetWithdraws(userID int64) ([]model.Withdraw, *model.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdraws", userID)
	ret0, _ := ret[0].([]model.Withdraw)
	ret1, _ := ret[1].(*model.APIError)
	return ret0, ret1
}

// GetWithdraws indicates an expected call of GetWithdraws.
func (mr *MockServiceMockRecorder) GetWithdraws(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdraws", reflect.TypeOf((*MockService)(nil).GetWithdraws), userID)
}

// Login mocks base method.
func (m *MockService) Login(input model.LoginDTO) (string, *model.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*model.APIError)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockServiceMockRecorder) Login(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockService)(nil).Login), input)
}

// Register mocks base method.
func (m *MockService) Register(input model.RegisterDTO) (string, *model.APIError) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", input)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(*model.APIError)
	return ret0, ret1
}

// Register indicates an expected call of Register.
func (mr *MockServiceMockRecorder) Register(input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockService)(nil).Register), input)
}

// SetWithdraw mocks base method.
func (m *MockService) SetWithdraw(userID int64, input model.SetWithdrawDTO) *model.APIError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWithdraw", userID, input)
	ret0, _ := ret[0].(*model.APIError)
	return ret0
}

// SetWithdraw indicates an expected call of SetWithdraw.
func (mr *MockServiceMockRecorder) SetWithdraw(userID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWithdraw", reflect.TypeOf((*MockService)(nil).SetWithdraw), userID, input)
}
