// Code generated by MockGen. DO NOT EDIT.
// Source: internal/service/service.go

// Package is a generated GoMock package.
package pg

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/ibeloyar/gophermart/internal/model"
)

// MockStorageRepo is a mock of StorageRepo interface.
type MockStorageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepoMockRecorder
}

// MockStorageRepoMockRecorder is the mock recorder for MockStorageRepo.
type MockStorageRepoMockRecorder struct {
	mock *MockStorageRepo
}

// NewMockStorageRepo creates a new mock instance.
func NewMockStorageRepo(ctrl *gomock.Controller) *MockStorageRepo {
	mock := &MockStorageRepo{ctrl: ctrl}
	mock.recorder = &MockStorageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepo) EXPECT() *MockStorageRepoMockRecorder {
	return m.recorder
}

// CreateOrder mocks base method.
func (m *MockStorageRepo) CreateOrder(userID int64, number string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", userID, number)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStorageRepoMockRecorder) CreateOrder(userID, number interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStorageRepo)(nil).CreateOrder), userID, number)
}

// CreateUser mocks base method.
func (m *MockStorageRepo) CreateUser(user model.User) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", user)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockStorageRepoMockRecorder) CreateUser(user interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockStorageRepo)(nil).CreateUser), user)
}

// GetBalanceByUserID mocks base method.
func (m *MockStorageRepo) GetBalanceByUserID(userID int64) (*model.Balance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalanceByUserID", userID)
	ret0, _ := ret[0].(*model.Balance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalanceByUserID indicates an expected call of GetBalanceByUserID.
func (mr *MockStorageRepoMockRecorder) GetBalanceByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalanceByUserID", reflect.TypeOf((*MockStorageRepo)(nil).GetBalanceByUserID), userID)
}

// GetOrdersByUserID mocks base method.
func (m *MockStorageRepo) GetOrdersByUserID(userID int64) ([]model.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrdersByUserID", userID)
	ret0, _ := ret[0].([]model.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrdersByUserID indicates an expected call of GetOrdersByUserID.
func (mr *MockStorageRepoMockRecorder) GetOrdersByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrdersByUserID", reflect.TypeOf((*MockStorageRepo)(nil).GetOrdersByUserID), userID)
}

// GetUserByLogin mocks base method.
func (m *MockStorageRepo) GetUserByLogin(login string) *model.User {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByLogin", login)
	ret0, _ := ret[0].(*model.User)
	return ret0
}

// GetUserByLogin indicates an expected call of GetUserByLogin.
func (mr *MockStorageRepoMockRecorder) GetUserByLogin(login interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByLogin", reflect.TypeOf((*MockStorageRepo)(nil).GetUserByLogin), login)
}

// GetWithdrawsByUserID mocks base method.
func (m *MockStorageRepo) GetWithdrawsByUserID(userID int64) ([]model.Withdraw, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithdrawsByUserID", userID)
	ret0, _ := ret[0].([]model.Withdraw)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithdrawsByUserID indicates an expected call of GetWithdrawsByUserID.
func (mr *MockStorageRepoMockRecorder) GetWithdrawsByUserID(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithdrawsByUserID", reflect.TypeOf((*MockStorageRepo)(nil).GetWithdrawsByUserID), userID)
}

// SetWithdraw mocks base method.
func (m *MockStorageRepo) SetWithdraw(userID int64, input model.SetWithdrawDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetWithdraw", userID, input)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetWithdraw indicates an expected call of SetWithdraw.
func (mr *MockStorageRepoMockRecorder) SetWithdraw(userID, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetWithdraw", reflect.TypeOf((*MockStorageRepo)(nil).SetWithdraw), userID, input)
}
